import React from 'react';
import { ContainerButton, TextClearSignal, TextSignalButton, TextSignalEqualButton, ButtonLine, ButtonNumber, TextNumberButton } from './style'

export default function numberButton(){
    return(
    <ContainerButton>
        <ButtonLine>
            <ButtonNumber>
                <TextClearSignal>C</TextClearSignal>
            </ButtonNumber>
            <ButtonNumber>
                <TextSignalButton>()</TextSignalButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextSignalButton>%</TextSignalButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextSignalButton>/</TextSignalButton>
            </ButtonNumber>
        </ButtonLine>
        <ButtonLine>
            <ButtonNumber>
                <TextNumberButton>7</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextNumberButton>8</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextNumberButton>9</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextSignalButton>*</TextSignalButton>
            </ButtonNumber>
        </ButtonLine>
        <ButtonLine>
            <ButtonNumber>
                <TextNumberButton>4</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextNumberButton>5</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextNumberButton>6</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextSignalButton>-</TextSignalButton>
            </ButtonNumber>
        </ButtonLine>
        <ButtonLine>
            <ButtonNumber>
                <TextNumberButton>1</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextNumberButton>2</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextNumberButton>3</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextSignalButton>+</TextSignalButton>
            </ButtonNumber>
        </ButtonLine>
        <ButtonLine>
            <ButtonNumber>
                <TextNumberButton>±</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextNumberButton>0</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextNumberButton>,</TextNumberButton>
            </ButtonNumber>
            <ButtonNumber>
                <TextSignalEqualButton>=</TextSignalEqualButton>
            </ButtonNumber>
        </ButtonLine>
    </ContainerButton>
        
    )
}